language: java
services: docker
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw
  - sudo apt-get update
  - docker-compose --version
  - chmod +x docker-compose
  - docker-compose --version
  - docker-compose up db
  - docker ps
  - echo 'done'
