language: java
services: docker
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw
  - sudo apt-get update
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo docker-compose up db
  - docker ps
  - echo 'done'
