language: java
services: docker
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw
  - sudo apt-get update
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - chmod +x docker-compose
  - sudo docker-compose --version
  - sudo docker-compose up db
  - sudo docker ps
  - echo 'done'
